use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::sync::Arc;
use std::time::Duration;

use anyhow::{Context, Result};
use tauri::{AppHandle, Emitter};
use tokio::sync::Mutex;

use crate::types::AudioDevice;

use crate::audio::{AudioCapture, AudioPlayback, MicTest};
use crate::peer::PeerConn;
use crate::signaling;
use crate::types::*;

const DEFAULT_SIGNALING_URL: &str = "wss://entavi-signaling.avdo.workers.dev/ws";
const ICE_QUEUE_MESSAGES: usize = 256;
const CONN_STATE_QUEUE_MESSAGES: usize = 32;

fn queue_signal(tx: &flume::Sender<SignalMessage>, msg: SignalMessage) -> Result<()> {
    match tx.try_send(msg) {
        Ok(()) => Ok(()),
        Err(flume::TrySendError::Full(_)) => Err(anyhow::anyhow!("Signal channel backlog is full")),
        Err(flume::TrySendError::Disconnected(_)) => Err(anyhow::anyhow!("Signal channel closed")),
    }
}

/// Engine is the central orchestrator stored in Tauri managed state.
pub struct Engine {
    inner: Arc<Mutex<Option<EngineInner>>>,
    app: AppHandle,
    /// Persists across sessions - not inside EngineInner.
    selected_input_device: std::sync::Mutex<Option<String>>,
    selected_output_device: std::sync::Mutex<Option<String>>,
    signaling_url: std::sync::Mutex<Option<String>>,
    mic_test: std::sync::Mutex<Option<MicTest>>,
    noise_suppression: Arc<AtomicBool>,
    vad_threshold: Arc<AtomicU32>,
    agc_enabled: Arc<AtomicBool>,
}

struct EngineInner {
    peer_id: String,
    peer_name: String,
    room_id: String,
    room_name: String,
    signal_tx: flume::Sender<SignalMessage>,
    peers: HashMap<String, Arc<PeerConn>>,
    capture: AudioCapture,
    playback: AudioPlayback,
    /// Channel for ICE candidates generated by any PeerConn
    ice_tx: flume::Sender<(String, SignalPayload)>,
    ice_rx: flume::Receiver<(String, SignalPayload)>,
    /// Channel for peer connection state changes
    conn_state_tx: flume::Sender<(
        String,
        webrtc::peer_connection::peer_connection_state::RTCPeerConnectionState,
    )>,
    conn_state_rx: flume::Receiver<(
        String,
        webrtc::peer_connection::peer_connection_state::RTCPeerConnectionState,
    )>,
    /// RTT measurements from signaling ping/pong
    rtt_rx: flume::Receiver<u64>,
    /// Signaling connection status
    signaling_status_rx: flume::Receiver<signaling::SignalingStatus>,
    /// TURN server credentials from signaling server
    turn_servers: Vec<TurnServerInfo>,
    is_host: bool,
    room_locked: bool,
}

impl Engine {
    pub fn new(app: AppHandle) -> Self {
        Self {
            inner: Arc::new(Mutex::new(None)),
            app,
            selected_input_device: std::sync::Mutex::new(None),
            selected_output_device: std::sync::Mutex::new(None),
            signaling_url: std::sync::Mutex::new(None),
            mic_test: std::sync::Mutex::new(None),
            noise_suppression: Arc::new(AtomicBool::new(true)),
            vad_threshold: Arc::new(AtomicU32::new(0.01f32.to_bits())),
            agc_enabled: Arc::new(AtomicBool::new(true)),
        }
    }

    pub fn set_signaling_url(&self, url: Option<String>) {
        *self.signaling_url.lock().unwrap() = url;
    }

    /// Create a new room. Returns the room_id (6-char code).
    pub async fn create_room(&self, room_name: String, name: String) -> Result<String> {
        let room_id = uuid::Uuid::new_v4().to_string()[..6].to_string();
        self.join_room_inner(room_id.clone(), room_name, name, None, true)
            .await?;
        Ok(room_id)
    }

    /// Join an existing room by room_id.
    pub async fn join_room(
        &self,
        room_id: String,
        name: String,
        password: Option<String>,
    ) -> Result<()> {
        let room_name = format!("Room {room_id}");
        self.join_room_inner(room_id, room_name, name, password, false)
            .await
    }

    async fn join_room_inner(
        &self,
        room_id: String,
        room_name: String,
        name: String,
        password: Option<String>,
        create: bool,
    ) -> Result<()> {
        // Stop mic test if running
        self.stop_mic_test();

        // Clean up any existing session
        self.leave_room().await?;

        let peer_id = uuid::Uuid::new_v4().to_string();

        self.emit_state(CallState::Connecting);

        // Start audio capture and playback
        let device_name = self.selected_input_device.lock().unwrap().clone();
        let output_device_name = self.selected_output_device.lock().unwrap().clone();
        let capture = AudioCapture::new(
            device_name,
            Arc::clone(&self.noise_suppression),
            Arc::clone(&self.vad_threshold),
            Arc::clone(&self.agc_enabled),
        )
        .context("Failed to start audio capture")?;
        let playback =
            AudioPlayback::new(output_device_name).context("Failed to start audio playback")?;

        // Connect to signaling server (room_id is part of the URL path)
        let base_url = self
            .signaling_url
            .lock()
            .unwrap()
            .clone()
            .unwrap_or_else(|| DEFAULT_SIGNALING_URL.to_string());
        let ws_url = format!("{base_url}/{room_id}");
        let (signal_tx, signal_rx, rtt_rx, signaling_status_rx) = signaling::connect(&ws_url)
            .await
            .context("Failed to connect to signaling server")?;

        // Send join message
        queue_signal(
            &signal_tx,
            SignalMessage::Join {
                room_id: room_id.clone(),
                peer_id: peer_id.clone(),
                name: name.clone(),
                password,
                create,
            },
        )
        .context("Failed to send join message")?;

        // ICE candidate channel shared across all peer connections
        let (ice_tx, ice_rx) = flume::bounded::<(String, SignalPayload)>(ICE_QUEUE_MESSAGES);

        // Peer connection state changes
        let (conn_state_tx, conn_state_rx) = flume::bounded(CONN_STATE_QUEUE_MESSAGES);

        let inner = EngineInner {
            peer_id,
            peer_name: name,
            room_id: room_id.clone(),
            room_name: room_name.clone(),
            signal_tx: signal_tx.clone(),
            peers: HashMap::new(),
            capture,
            playback,
            ice_tx,
            ice_rx,
            conn_state_tx,
            conn_state_rx,
            rtt_rx,
            signaling_status_rx,
            turn_servers: Vec::new(),
            is_host: false,
            room_locked: false,
        };

        *self.inner.lock().await = Some(inner);

        // Start the engine event loop
        let engine_inner = Arc::clone(&self.inner);
        let app = self.app.clone();

        tokio::spawn(async move {
            if let Err(e) = engine_loop(engine_inner, signal_rx, signal_tx, app.clone()).await {
                tracing::error!("Engine loop error: {e}");
                let _ = app.emit(EVENT_ERROR, format!("{e}"));
            }
        });

        // For creates, we can show InRoom immediately (we know the room exists).
        // For joins, wait for the server's RoomJoined response before switching views.
        if create {
            self.emit_state(CallState::InRoom {
                room_id,
                room_name,
                is_host: false,
                locked: false,
            });
        }

        Ok(())
    }

    pub async fn leave_room(&self) -> Result<()> {
        let inner = {
            let mut guard = self.inner.lock().await;
            guard.take()
        };

        if let Some(inner) = inner {
            // Send leave signal
            let _ = queue_signal(
                &inner.signal_tx,
                SignalMessage::Leave {
                    room_id: inner.room_id.clone(),
                    peer_id: inner.peer_id.clone(),
                },
            );

            // Close all peer connections
            for (_, peer) in inner.peers {
                peer.close().await;
            }

            self.emit_state(CallState::Idle);
        }
        Ok(())
    }

    pub async fn set_muted(&self, muted: bool) -> Result<()> {
        let guard = self.inner.lock().await;
        if let Some(inner) = guard.as_ref() {
            inner.capture.set_muted(muted);
            // Broadcast mute state to all peers via signaling
            let _ = queue_signal(&inner.signal_tx, SignalMessage::MuteState { muted });
        }
        Ok(())
    }

    /// Store the preferred input device. If currently in a call, restart capture.
    pub async fn set_input_device(&self, name: Option<String>) -> Result<()> {
        {
            let mut dev = self.selected_input_device.lock().unwrap();
            *dev = name.clone();
        }

        // If we're in a call, restart the capture thread with the new device.
        let in_call = self.inner.lock().await.is_some();
        if in_call {
            let new_capture = AudioCapture::new(
                name,
                Arc::clone(&self.noise_suppression),
                Arc::clone(&self.vad_threshold),
                Arc::clone(&self.agc_enabled),
            )
            .context("Failed to restart audio capture")?;

            let mut guard = self.inner.lock().await;
            if let Some(inner) = guard.as_mut() {
                // Replace capture - old one is dropped, its thread exits when
                // the encoded_tx sender side is dropped (receiver gone).
                inner.capture = new_capture;
                tracing::info!("Restarted audio capture with new input device");
            }
        }

        Ok(())
    }

    pub fn list_input_devices(&self) -> Vec<AudioDevice> {
        crate::audio::list_input_devices()
    }

    pub fn start_mic_test(&self) -> Result<()> {
        // Stop any existing test first
        self.stop_mic_test();
        let device_name = self.selected_input_device.lock().unwrap().clone();
        let output_device_name = self.selected_output_device.lock().unwrap().clone();
        let test = MicTest::new(
            device_name,
            output_device_name,
            self.app.clone(),
            Arc::clone(&self.noise_suppression),
        )?;
        *self.mic_test.lock().unwrap() = Some(test);
        Ok(())
    }

    pub fn set_noise_suppression(&self, enabled: bool) {
        self.noise_suppression.store(enabled, Ordering::Relaxed);
    }

    pub fn list_output_devices(&self) -> Vec<AudioDevice> {
        crate::audio::list_output_devices()
    }

    pub async fn set_output_device(&self, name: Option<String>) -> Result<()> {
        {
            let mut dev = self.selected_output_device.lock().unwrap();
            *dev = name.clone();
        }

        // If we're in a call, restart the playback thread with the new device.
        let in_call = self.inner.lock().await.is_some();
        if in_call {
            let new_playback =
                AudioPlayback::new(name).context("Failed to restart audio playback")?;

            let mut guard = self.inner.lock().await;
            if let Some(inner) = guard.as_mut() {
                // Replace playback - old one is dropped, its thread exits when
                // the tx sender side is dropped (receiver gone).
                inner.playback = new_playback;
                tracing::info!("Restarted audio playback with new output device");
            }
        }

        Ok(())
    }

    pub fn stop_mic_test(&self) {
        if let Some(test) = self.mic_test.lock().unwrap().take() {
            test.stop();
        }
    }

    fn emit_state(&self, state: CallState) {
        let _ = self.app.emit(EVENT_STATE_CHANGED, &state);
    }
}

/// Main engine event loop. Runs as a tokio task.
async fn engine_loop(
    engine: Arc<Mutex<Option<EngineInner>>>,
    signal_rx: flume::Receiver<SignalMessage>,
    signal_tx: flume::Sender<SignalMessage>,
    app: AppHandle,
) -> Result<()> {
    let mut mix_interval = tokio::time::interval(Duration::from_millis(20));
    mix_interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
    mix_interval.tick().await;

    let mut voice_activity_interval = tokio::time::interval(Duration::from_millis(100));
    voice_activity_interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
    voice_activity_interval.tick().await;

    let mut audio_peers = Vec::new();
    let mut mixed = [0.0f32; FRAME_SIZE];
    let mut speaking_peers = Vec::new();

    loop {
        let mut emit_voice_activity = false;

        // Get channels from inner (if still active)
        let (encoded_rx, ice_rx, conn_state_rx, rtt_rx, signaling_status_rx) = {
            let guard = engine.lock().await;
            let Some(inner) = guard.as_ref() else {
                break; // Engine shut down
            };
            (
                inner.capture.encoded_rx.clone(),
                inner.ice_rx.clone(),
                inner.conn_state_rx.clone(),
                inner.rtt_rx.clone(),
                inner.signaling_status_rx.clone(),
            )
        };

        tokio::select! {
            // ── Mixer tick keeps remote playback draining even when local capture is muted ──
            _ = mix_interval.tick() => {}

            // ── Voice activity tick ──
            _ = voice_activity_interval.tick() => {
                emit_voice_activity = true;
            }

            // ── Signaling message from server ──
            msg = signal_rx.recv_async() => {
                match msg {
                    Ok(msg) => {
                        handle_signal_message(&engine, &signal_tx, &app, msg).await?;
                    }
                    Err(_) => {
                        // Channel closed - signaling client dropped. Wait for status or exit.
                        tracing::warn!("Signal rx closed, engine will exit");
                        break;
                    }
                }
            }

            // ── Encoded audio from microphone ──
            frame = encoded_rx.recv_async() => {
                let Ok(frame) = frame else { break };
                audio_peers.clear();
                {
                    let guard = engine.lock().await;
                    if let Some(inner) = guard.as_ref() {
                        audio_peers.extend(inner.peers.values().cloned());
                    }
                }

                for peer in &audio_peers {
                    if let Err(e) = peer.send_audio(&frame).await {
                        tracing::warn!("Failed to send audio to {}: {e}", peer.peer_id);
                    }
                }
                audio_peers.clear();
            }

            // ── ICE candidate from one of our peer connections ──
            ice = ice_rx.recv_async() => {
                let Ok((target_peer_id, payload)) = ice else { break };
                let _ = queue_signal(
                    &signal_tx,
                    SignalMessage::Signal {
                        to: Some(target_peer_id),
                        from: None,
                        payload,
                    },
                );
            }

            // ── Peer connection state change ──
            conn_state = conn_state_rx.recv_async() => {
                if let Ok((peer_id, state)) = conn_state {
                    use webrtc::peer_connection::peer_connection_state::RTCPeerConnectionState;
                    if state == RTCPeerConnectionState::Failed {
                        tracing::warn!("Peer {peer_id} connection failed, attempting ICE restart");
                        let peer = {
                            let guard = engine.lock().await;
                            guard
                                .as_ref()
                                .and_then(|inner| inner.peers.get(&peer_id).cloned())
                        };
                        if let Some(peer) = peer {
                            match peer.restart_ice().await {
                                Ok(sdp) => {
                                    let _ = queue_signal(
                                        &signal_tx,
                                        SignalMessage::Signal {
                                            to: Some(peer_id),
                                            from: None,
                                            payload: SignalPayload::Offer { sdp },
                                        },
                                    );
                                }
                                Err(e) => {
                                    tracing::error!("ICE restart failed for {}: {e}", peer.peer_id);
                                }
                            }
                        }
                    }
                }
            }

            // ── Signaling connection status ──
            status = signaling_status_rx.recv_async() => {
                if let Ok(status) = status {
                    match status {
                        signaling::SignalingStatus::Connected => {
                            tracing::info!("Signaling reconnected, re-sending Join");
                            let guard = engine.lock().await;
                            if let Some(inner) = guard.as_ref() {
                                let _ = queue_signal(
                                    &signal_tx,
                                    SignalMessage::Join {
                                        room_id: inner.room_id.clone(),
                                        peer_id: inner.peer_id.clone(),
                                        name: inner.peer_name.clone(),
                                        password: None,
                                        create: false,
                                    },
                                );
                            }
                        }
                        signaling::SignalingStatus::Disconnected => {
                            tracing::warn!("Signaling disconnected");
                            let guard = engine.lock().await;
                            if let Some(inner) = guard.as_ref() {
                                let _ = app.emit(EVENT_STATE_CHANGED, CallState::Reconnecting {
                                    room_id: inner.room_id.clone(),
                                    room_name: inner.room_name.clone(),
                                    attempt: 0,
                                });
                            }
                        }
                        signaling::SignalingStatus::Reconnecting { attempt } => {
                            tracing::info!("Signaling reconnecting, attempt {attempt}");
                            let guard = engine.lock().await;
                            if let Some(inner) = guard.as_ref() {
                                let _ = app.emit(EVENT_STATE_CHANGED, CallState::Reconnecting {
                                    room_id: inner.room_id.clone(),
                                    room_name: inner.room_name.clone(),
                                    attempt,
                                });
                            }
                        }
                        signaling::SignalingStatus::Failed => {
                            tracing::error!("Signaling reconnection failed permanently");
                            let _ = app.emit(EVENT_STATE_CHANGED, CallState::Error {
                                message: "Connection lost - could not reconnect".to_string(),
                            });
                            break;
                        }
                    }
                }
            }

            // ── RTT measurement from signaling ping/pong ──
            rtt = rtt_rx.recv_async() => {
                if let Ok(rtt_ms) = rtt {
                    let _ = app.emit(EVENT_PING_UPDATE, rtt_ms);
                }
            }
        }

        // ── Mix decoded audio from all remote peers into playback ──
        {
            let guard = engine.lock().await;
            if let Some(inner) = guard.as_ref() {
                mixed.fill(0.0);
                let mut has_audio = false;
                speaking_peers.clear();

                for (peer_id, peer) in &inner.peers {
                    let mut peer_peak: f32 = 0.0;
                    let mut peer_has_audio = false;

                    while let Ok(frame) = peer.decoded_rx.try_recv() {
                        has_audio = true;
                        peer_has_audio = true;
                        let len = frame.len.min(frame.samples.len());
                        for (i, sample) in frame.samples[..len].iter().enumerate() {
                            peer_peak = peer_peak.max(sample.abs());
                            mixed[i] += *sample;
                        }
                    }

                    if peer_has_audio && peer_peak > 0.01 {
                        speaking_peers.push(peer_id.clone());
                    }
                }

                if has_audio {
                    // Clamp to [-1.0, 1.0]
                    for s in &mut mixed {
                        *s = s.clamp(-1.0, 1.0);
                    }
                    inner.playback.write(mixed);
                }

                if emit_voice_activity {
                    let self_speaking = inner.capture.is_speaking();
                    let _ = app.emit(
                        EVENT_VOICE_ACTIVITY,
                        VoiceActivityEvent {
                            speaking: speaking_peers.clone(),
                            self_speaking,
                        },
                    );
                }
            }
        }
    }

    Ok(())
}

async fn handle_signal_message(
    engine: &Arc<Mutex<Option<EngineInner>>>,
    signal_tx: &flume::Sender<SignalMessage>,
    app: &AppHandle,
    msg: SignalMessage,
) -> Result<()> {
    match msg {
        SignalMessage::RoomJoined {
            room_id,
            peers,
            is_host,
            locked,
            turn_servers,
        } => {
            tracing::info!("Joined room {room_id} with existing peers: {peers:?}, is_host: {is_host}, locked: {locked}, turn_servers: {}", turn_servers.len());

            // Store host/locked state and TURN servers
            {
                let mut guard = engine.lock().await;
                if let Some(inner) = guard.as_mut() {
                    inner.is_host = is_host;
                    inner.room_locked = locked;
                    inner.turn_servers = turn_servers;
                }
            }

            // Emit peer-joined for each existing peer so frontend builds its peer list
            for peer_info in &peers {
                let _ = app.emit(EVENT_PEER_JOINED, peer_info);
            }

            // We are the new joiner - send offers to all existing peers
            for peer_info in &peers {
                let peer = create_peer_conn(engine, peer_info.peer_id.clone()).await?;
                let sdp = peer.create_offer().await?;
                queue_signal(
                    signal_tx,
                    SignalMessage::Signal {
                        to: Some(peer_info.peer_id.clone()),
                        from: None,
                        payload: SignalPayload::Offer { sdp },
                    },
                )?;
            }

            // Update state with peer count
            let guard = engine.lock().await;
            if let Some(inner) = guard.as_ref() {
                let _ = app.emit(
                    EVENT_STATE_CHANGED,
                    CallState::InRoom {
                        room_id: inner.room_id.clone(),
                        room_name: inner.room_name.clone(),
                        is_host: inner.is_host,
                        locked: inner.room_locked,
                    },
                );
            }
        }

        SignalMessage::PeerJoined {
            peer_id,
            name,
            is_host,
        } => {
            tracing::info!("Peer {peer_id} ({name}) joined - waiting for their offer");
            let _ = app.emit(
                EVENT_PEER_JOINED,
                PeerInfo {
                    peer_id: peer_id.clone(),
                    name,
                    is_host,
                },
            );

            let guard = engine.lock().await;
            if let Some(inner) = guard.as_ref() {
                let _ = app.emit(
                    EVENT_STATE_CHANGED,
                    CallState::InRoom {
                        room_id: inner.room_id.clone(),
                        room_name: inner.room_name.clone(),
                        is_host: inner.is_host,
                        locked: inner.room_locked,
                    },
                );
            }
        }

        SignalMessage::PeerLeft { peer_id } => {
            tracing::info!("Peer {peer_id} left");
            let _ = app.emit(EVENT_PEER_LEFT, &peer_id);

            let (peer, state) = {
                let mut guard = engine.lock().await;
                if let Some(inner) = guard.as_mut() {
                    let peer = inner.peers.remove(&peer_id);
                    let state = Some(CallState::InRoom {
                        room_id: inner.room_id.clone(),
                        room_name: inner.room_name.clone(),
                        is_host: inner.is_host,
                        locked: inner.room_locked,
                    });
                    (peer, state)
                } else {
                    (None, None)
                }
            };

            if let Some(peer) = peer {
                peer.close().await;
            }

            if let Some(state) = state {
                let _ = app.emit(EVENT_STATE_CHANGED, state);
            }
        }

        SignalMessage::RoomNotFound => {
            tracing::info!("Room does not exist");

            let inner = {
                let mut guard = engine.lock().await;
                guard.take()
            };
            if let Some(inner) = inner {
                for (_, peer) in inner.peers {
                    peer.close().await;
                }
            }

            let _ = app.emit(
                EVENT_STATE_CHANGED,
                CallState::Error {
                    message: "Room not found".to_string(),
                },
            );
        }

        SignalMessage::PeerMuteState { peer_id, muted } => {
            tracing::info!("Peer {peer_id} mute state changed: {muted}");
            let _ = app.emit(EVENT_PEER_MUTE_CHANGED, PeerMuteEvent { peer_id, muted });
        }

        SignalMessage::Signal {
            from: Some(from),
            payload,
            ..
        } => {
            handle_signal_payload(engine, signal_tx, &from, payload).await?;
        }

        // Client-originating messages or unrecognized
        _ => {}
    }

    Ok(())
}

async fn handle_signal_payload(
    engine: &Arc<Mutex<Option<EngineInner>>>,
    signal_tx: &flume::Sender<SignalMessage>,
    from: &str,
    payload: SignalPayload,
) -> Result<()> {
    match payload {
        SignalPayload::Offer { sdp } => {
            tracing::info!("Received offer from {from}");

            // Create peer conn if we don't have one yet
            let peer = {
                let guard = engine.lock().await;
                let inner = guard.as_ref().context("Engine not active")?;
                inner.peers.get(from).cloned()
            };

            let peer = if let Some(p) = peer {
                p
            } else {
                create_peer_conn(engine, from.to_string()).await?
            };

            let answer_sdp = peer.handle_offer(&sdp).await?;

            queue_signal(
                signal_tx,
                SignalMessage::Signal {
                    to: Some(from.to_string()),
                    from: None,
                    payload: SignalPayload::Answer { sdp: answer_sdp },
                },
            )?;
        }

        SignalPayload::Answer { sdp } => {
            tracing::info!("Received answer from {from}");
            let peer = {
                let guard = engine.lock().await;
                let inner = guard.as_ref().context("Engine not active")?;
                inner.peers.get(from).cloned()
            };
            if let Some(peer) = peer {
                peer.handle_answer(&sdp).await?;
            }
        }

        SignalPayload::IceCandidate {
            candidate,
            sdp_mid,
            sdp_mline_index,
        } => {
            let peer = {
                let guard = engine.lock().await;
                let inner = guard.as_ref().context("Engine not active")?;
                inner.peers.get(from).cloned()
            };
            if let Some(peer) = peer {
                peer.add_ice_candidate(&candidate, sdp_mid, sdp_mline_index)
                    .await?;
            }
        }
    }

    Ok(())
}

/// Create a new PeerConn, store it in the engine, and return a reference.
async fn create_peer_conn(
    engine: &Arc<Mutex<Option<EngineInner>>>,
    remote_peer_id: String,
) -> Result<Arc<PeerConn>> {
    let (ice_tx, conn_state_tx, turn_servers) = {
        let guard = engine.lock().await;
        let inner = guard.as_ref().context("Engine not active")?;
        (
            inner.ice_tx.clone(),
            inner.conn_state_tx.clone(),
            inner.turn_servers.clone(),
        )
    };

    let peer = Arc::new(
        PeerConn::new(remote_peer_id.clone(), ice_tx, &turn_servers, conn_state_tx).await?,
    );

    {
        let mut guard = engine.lock().await;
        let inner = guard.as_mut().context("Engine not active")?;
        inner.peers.insert(remote_peer_id, Arc::clone(&peer));
    }

    Ok(peer)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn queue_signal_reports_full_backlog_without_blocking() {
        let (tx, _rx) = flume::bounded(0);

        let err = queue_signal(&tx, SignalMessage::RoomNotFound).unwrap_err();

        assert!(err.to_string().contains("backlog is full"));
    }

    #[test]
    fn queue_signal_reports_closed_channel() {
        let (tx, rx) = flume::bounded(1);
        drop(rx);

        let err = queue_signal(&tx, SignalMessage::RoomNotFound).unwrap_err();

        assert!(err.to_string().contains("closed"));
    }
}
